PH-74 Add example for variants JSON
findologic/plugin-shopware-5-extension pull request #6
Opened 2020-12-11 09:14 UTC by TobiasGraml11

2020-12-11 11:33 UTC, TheKeymaster requested changes

2020-12-14 09:39 UTC, TobiasGraml11 commented on ExtendFinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +    // The variant column the variants should be differentiated by
This comment should be exactly that
I changed it, maybe it makes more sense now

2020-12-14 09:49 UTC, TobiasGraml11 commented on ExtendFinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                new Property('variants', ['' => json_encode($variants)])
The empty string is the default usergroup, which is needed for properties

2020-12-14 09:52 UTC, TheKeymaster commented on ExtendFinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                new Property('variants', ['' => json_encode($variants)])
You're obviously right.

2020-12-14 09:54 UTC, TheKeymaster approved these changes

2020-12-14 10:46 UTC, TheKeymaster requested changes

2020-12-14 10:46 UTC, TheKeymaster commented on ExtendFinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +     *     "images": [
Since there is also now `thumbnails`, please add them here to the example as well.

2021-04-22 08:01 UTC, TheKeymaster approved these changes

2021-04-22 08:03 UTC, merged